import { Schedule } from "./schedule";
import {
    ACTIVITY_DEPENDENCY_TYPE,
    ACTIVITY_STATUS,
    ACTIVITY_TYPE,
} from "./enums";
import {
    ITaskData,
    ScheduleDataParser,
    IScheduleData,
    IActivityDependencyData,
    IActivityData,
    GanttDataParser,
    IGanttTask,
} from "./parser";

export {
    ITaskData,
    ACTIVITY_DEPENDENCY_TYPE,
    IActivityDependencyData,
    IActivityData,
    IScheduleData,
    ACTIVITY_STATUS,
};

export class GanttTaskDataProcessor {
    public static process_gantt_task_data(tree: ITaskData): ITaskData {
        console.log("Tree Received", tree);
        if (tree.data.length <= 1) {
            console.log("No sufficient data to process");
            return tree;
        }
        const parser = new GanttDataParser();
        let schedule: Schedule = parser.get_schedule_from_gantt_task_data(tree);
        console.log("Schedule Created, Processing started");
        schedule.process();
        console.log(
            "Schedule Planned Start and End Dates",
            schedule.activity_map.get(schedule.root_id)?.planned_start_date,
            schedule.activity_map.get(schedule.root_id)?.planned_end_date
        );
        console.log(
            "Schedule Projected Start and End Dates",
            schedule.activity_map
                .get(schedule.root_id)
                ?.get_projected_start_date(),
            schedule.activity_map
                .get(schedule.root_id)
                ?.get_projected_end_date()
        );
        console.log(
            "Schedule Actual Start and End Dates",
            schedule.activity_map.get(schedule.root_id)?.actual_start_date,
            schedule.activity_map.get(schedule.root_id)?.actual_end_date
        );
        console.log(
            "Schedule Completion and status",
            schedule.activity_map.get(schedule.root_id)?.completion_percentage,
            schedule.activity_map.get(schedule.root_id)?.get_status()
        );
        let result_tree = parser.get_gantt_task_data_from_schedule(schedule);
        console.log("Result Tree", result_tree);
        return result_tree;
    }

    public static detect_cycle(tree: ITaskData): boolean {
        console.log("Tree Received", tree);
        if (tree.data.length <= 1) {
            console.log("No sufficient data to process");
            return false;
        }
        const parser = new GanttDataParser();
        let schedule: Schedule = parser.get_schedule_from_gantt_task_data(tree);
        console.log("Schedule Created, Cycle detection started");
        let has_cycle = schedule.detect_cycle();
        console.log("Cycle Detected: ", has_cycle);
        return has_cycle;
    }
}

const tree = {
    root_id: "0",
    data: [
        {
            id: "0",
        },
        {
            id: "1",
            text: "New activity",
            start_date: new Date("2025-03-26T18:30:00.000Z"),
            end_date: new Date("2025-03-27T18:30:00.000Z"),
            duration: 1,
            progress: 0,
            assignees: [],
            organizations: [],
            actual_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_end_date: new Date("2025-03-26T18:30:00.000Z"),
            slack: 0,
            color: "#9689B2",
            status: "ON_TIME",
            type: ACTIVITY_TYPE.PROJECT,
            open: false,
            wbs: "1",
            editField: null,
            isCritical: true,
            attachments: [],
            delay_by: 0,
            selected: false,
            dependencies: [],
        },
        {
            id: "2",
            text: "New activity",
            start_date: new Date("2025-03-26T18:30:00.000Z"),
            end_date: new Date("2025-03-27T18:30:00.000Z"),
            duration: 1,
            progress: 0.5,
            parent: "1",
            assignees: [],
            organizations: [],
            actual_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_end_date: new Date("2025-03-26T18:30:00.000Z"),
            slack: 0,
            color: "#9689B2",
            status: "ON_TIME",
            type: ACTIVITY_TYPE.PROJECT,
            open: false,
            wbs: "1.1",
            editField: null,
            isCritical: true,
            attachments: [],
            delay_by: 0,
            selected: false,
            dependencies: [],
        },
        {
            id: "3",
            text: "New activity",
            start_date: new Date("2025-03-26T18:30:00.000Z"),
            end_date: new Date("2025-03-27T18:30:00.000Z"),
            duration: 1,
            progress: 1,
            parent: "2",
            assignees: [],
            organizations: [],
            actual_start_date: new Date("2025-03-26T18:30:00.000Z"),
            actual_end_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_end_date: new Date("2025-03-26T18:30:00.000Z"),
            slack: 0,
            color: "#9689B2",
            status: "ON_TIME",
            type: ACTIVITY_TYPE.TASK,
            open: false,
            wbs: "1.1.1",
            editField: null,
            isCritical: true,
            attachments: [],
            delay_by: 0,
            selected: false,
            dependencies: [],
        },
        {
            id: "4",
            text: "New activity",
            start_date: new Date("2025-03-26T18:30:00.000Z"),
            end_date: new Date("2025-03-27T18:30:00.000Z"),
            duration: 1,
            progress: 1,
            parent: "2",
            assignees: [],
            organizations: [],
            actual_start_date: new Date("2025-03-26T18:30:00.000Z"),
            actual_end_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_start_date: new Date("2025-03-26T18:30:00.000Z"),
            projected_end_date: new Date("2025-03-26T18:30:00.000Z"),
            slack: 0,
            color: "#9689B2",
            status: "ON_TIME",
            type: ACTIVITY_TYPE.TASK,
            open: false,
            wbs: "1.1.2",
            editField: null,
            prevSibling: "3",
            isCritical: true,
            attachments: [],
            delay_by: 0,
            selected: false,
            dependencies: [],
        },
    ],
    links: [
        {
            source: "1",
            lag: 0,
            target: "2",
            type: ACTIVITY_DEPENDENCY_TYPE.FS,
        }
    ],
};
// GanttTaskDataProcessor.process_gantt_task_data(tree);

const tree_have_cycle = {
    root_id: "0",
    data: [
        {
            id: "0",
        },
        {
            id: "1",
            parent: "0",
        },
        {
            id: "2",
            parent: "0",
        },
        {
            id: "3",
            parent: "1",
        },
        {
            id: "4",
            parent: "1",
        },
    ],
    links: [
        {
            source: "3",
            target: "4",
            type: ACTIVITY_DEPENDENCY_TYPE.FS,
            lag: 0,
        },
        {
            source: "2",
            target: "4",
            type: ACTIVITY_DEPENDENCY_TYPE.FS,
            lag: 0,
        },
        {
            source: "1",
            target: "2",
            type: ACTIVITY_DEPENDENCY_TYPE.FS,
            lag: 0,
        },
    ],
};

// GanttTaskDataProcessor.detect_cycle(tree_have_cycle);

export class ProjectScheduleProcessor {
    public static process_project_schedule_data(
        schedule_data: IScheduleData
    ): IScheduleData {
        if (schedule_data.activities.length <= 1) {
            console.log("No sufficient data to process");
            return schedule_data;
        }
        const parser = new ScheduleDataParser();
        let schedule = parser.get_schedule_from_schedule_data(schedule_data);
        schedule.process();
        console.log(
            "Schedule Planned Start and End Dates",
            schedule.activity_map.get(schedule.root_id)?.planned_start_date,
            schedule.activity_map.get(schedule.root_id)?.planned_end_date
        );
        console.log(
            "Schedule Projected Start and End Dates",
            schedule.activity_map
                .get(schedule.root_id)
                ?.get_projected_start_date(),
            schedule.activity_map
                .get(schedule.root_id)
                ?.get_projected_end_date()
        );
        console.log(
            "Schedule Actual Start and End Dates",
            schedule.activity_map.get(schedule.root_id)?.actual_start_date,
            schedule.activity_map.get(schedule.root_id)?.actual_end_date
        );
        console.log(
            `Schedule Completion ${
                schedule.activity_map.get(schedule.root_id)
                    ?.completion_percentage
            }, status ${schedule.activity_map
                .get(schedule.root_id)
                ?.get_status()},
            by ${schedule.activity_map.get(schedule.root_id)?.get_delayed_by()}
            `
        );
        let final_schedule_data =
            parser.get_schedule_data_from_schedule(schedule);
        return final_schedule_data;
    }
}
/*
let project_schedule = {
    uuid: "478e01dc-6834-458d-a754-989bad1b112e",
    activities: [
        {
            id: "ng3XGvlK1BbK8oJ4",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "GgDXzqGA8xvN1wnJ",
            uuid: "fca4121e-7ead-4328-9deb-bccc78fb331f",
            name: "Schematic Layouts",
            wbs: "25",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "7f58eb55-f597-42af-a2b6-fbce7bddb070",
            is_critical: false,
            planned_start_date: "2024-09-06",
            planned_end_date: "2024-09-06",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 38,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "KnwAN0b74XvQ65DP",
                    updated_by_id: "71YXeqPgmwjRAKPd",
                    dependency_uuid: "d7ee0933-d6c0-4b1e-8827-5d9fc65600a9",
                    uuid: "54fccb70-e7a8-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FF",
                    updated_at: "2025-02-10T12:13:33.819878Z",
                },
            ],
            comment_count: 0,
        },
        {
            id: "pzYgovE486b1X3Bk",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "aV5dKqDA80bM2GgX",
            uuid: "7c683ac2-5dd8-43b8-917b-4d061d7778f2",
            name: "Kick off meeting on site - site kick-off presentation, site handover report.",
            wbs: "32",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "002bdc0a-a291-48f7-b4fc-abb3fc9267a5",
            is_critical: false,
            planned_start_date: "2024-09-12",
            planned_end_date: "2024-09-14",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 35,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "OWwk3djRlabaZARL",
                    updated_by_id: undefined,
                    dependency_uuid: "ad0e87eb-2366-42f8-9dbe-00e141f386bf",
                    uuid: "2957ef20-e7aa-11ef-8158-77bdfda655ac",
                    lag: -2,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "GQ3JwqJNaQqem8dB",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "dgnypvMNVpjozLVM",
            uuid: "d086ed5d-3a82-4df2-a046-82e1e7fae594",
            name: "Waterproofing & Brick Bat Coba",
            wbs: "37",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
            is_critical: false,
            planned_start_date: "2024-09-19",
            planned_end_date: "2024-09-23",
            duration: 5,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 27,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "KnwAN0b74QvQ65DP",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "dbcb3900-e7aa-11ef-8158-77bdfda655ac",
                    lag: -4,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "dgnypvMNVpjozLVM",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "d6MwBqLeRLbV8JkK",
            uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
            name: "Masonary Works",
            wbs: "36",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f3d4e49b-9960-4e6f-b98b-1293ebe6be4c",
            is_critical: true,
            planned_start_date: "2024-09-14",
            planned_end_date: "2024-09-22",
            duration: 9,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "apzYgovENnj1X3Bk",
                    updated_by_id: undefined,
                    dependency_uuid: "f3d4e49b-9960-4e6f-b98b-1293ebe6be4c",
                    uuid: "b13fcde0-e7aa-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "rBAdKboV6nqLe7Og",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "rzKaQv51Mov17YWX",
            uuid: "4c984be3-79d2-4491-afbe-20c99feaa925",
            name: "Sign-off on Master Project Schedule.",
            wbs: "9",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "078d6e2a-c00e-4f5a-9aec-ebe242ffbc99",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-07",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 43,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "m6MWy2q2QGj7aJYN",
                    updated_by_id: undefined,
                    dependency_uuid: "078d6e2a-c00e-4f5a-9aec-ebe242ffbc99",
                    uuid: "ad9013b0-e7a7-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "a3zM2bNGXVvBQXy1",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "nwAN0b70DwvQ65DP",
            uuid: "4be85522-3025-4abf-bd2e-628efd21b455",
            name: "Sample Submissions & Approval of Mock Up of Finish Matrix",
            wbs: "34",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "d354e981-bf62-450d-bfba-afa97ef809b4",
            is_critical: false,
            planned_start_date: "2024-09-09",
            planned_end_date: "2024-09-11",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 39,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "X76DlLjXDxj39ogd",
                    updated_by_id: undefined,
                    dependency_uuid: "002bdc0a-a291-48f7-b4fc-abb3fc9267a5",
                    uuid: "4b3cd830-e7aa-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "d6MwBqLeRLbV8JkK",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "a3zM2bNGXVvBQXy1",
            uuid: "f3d4e49b-9960-4e6f-b98b-1293ebe6be4c",
            name: "Preliminary site activities- LINE OUT MARKING ETC",
            wbs: "35",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "4be85522-3025-4abf-bd2e-628efd21b455",
            is_critical: true,
            planned_start_date: "2024-09-12",
            planned_end_date: "2024-09-14",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "JaV5dKqD7OjM2GgX",
                    updated_by_id: undefined,
                    dependency_uuid: "ad0e87eb-2366-42f8-9dbe-00e141f386bf",
                    uuid: "640042d0-e7aa-11ef-8158-77bdfda655ac",
                    lag: -2,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "DeOyQqeY4aqm4LrW",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "GQ3JwqJNaQqem8dB",
            uuid: "484f648a-8f08-4ea4-8371-f7fc899c5e7e",
            name: "Wall Preparation",
            wbs: "38",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "d086ed5d-3a82-4df2-a046-82e1e7fae594",
            is_critical: false,
            planned_start_date: "2024-09-23",
            planned_end_date: "2024-10-07",
            duration: 15,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "ea3zM2bNEZqBQXy1",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "eb50c390-e7aa-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "zrOVQjnrBAjd25m6",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "71YXeqPaElbRAKPd",
            uuid: "f067dd2c-d059-4a06-bd34-5515ad834b8d",
            name: "Partition Work (Gypsum & Glass)",
            wbs: "40",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "5c47e6fa-8d5c-4e96-bc88-7043a913a0ac",
            is_critical: true,
            planned_start_date: "2024-09-18",
            planned_end_date: "2024-10-02",
            duration: 15,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "OdgnypvMDwbozLVM",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "08ddc430-e7ab-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "wp8LYbxVWJjnlGK6",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "8po94bYA0abarJe3",
            uuid: "bc964dff-d860-425d-b26b-4063444d4bb6",
            name: "Light Fixtures",
            wbs: "48",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "256c2cf4-57f1-4146-8b56-b19aaf8e51ad",
            is_critical: false,
            planned_start_date: "2024-10-05",
            planned_end_date: "2024-10-14",
            duration: 10,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "WgPVoxb814v91RA4",
                    updated_by_id: undefined,
                    dependency_uuid: "f8078073-3118-4a81-9d97-40fdf5400892",
                    uuid: "8c6a8630-e7ab-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "rBAdKboVynqLe7Og",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "rzKaQv51Vov17YWX",
            uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
            name: "DEEP CLEANING",
            wbs: "53",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "9e25e29d-d3a8-4cc4-ac5b-b2187fe55104",
            is_critical: true,
            planned_start_date: "2024-10-16",
            planned_end_date: "2024-10-18",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "3P1DN7jyWpbzn0aA",
                    updated_by_id: "71YXeqPgmwjRAKPd",
                    dependency_uuid: "f1088afd-0dd0-4768-ac9d-631b54ea3a4a",
                    uuid: "ec188af0-e7ab-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: "2025-02-10T12:38:46.624547Z",
                },
            ],
            comment_count: 0,
        },
        {
            id: "1ZnElq6DXgvo35Bg",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "zrOVQjnrBAjd25m6",
            uuid: "f8078073-3118-4a81-9d97-40fdf5400892",
            name: "False Ceiling Works",
            wbs: "41",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f067dd2c-d059-4a06-bd34-5515ad834b8d",
            is_critical: true,
            planned_start_date: "2024-09-28",
            planned_end_date: "2024-10-09",
            duration: 12,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "9GQ3JwqJRkqem8dB",
                    updated_by_id: undefined,
                    dependency_uuid: "f067dd2c-d059-4a06-bd34-5515ad834b8d",
                    uuid: "16951e70-e7ab-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "gPVoxb8WENq91RA4",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "NkErBq0zGyvaLJ09",
            uuid: "6562fc95-98e7-419f-bd43-31221131b420",
            name: "Retro Fittout Items ( Roller Blind,Graphics,Artwork,Wall Paper,Back Painted Glass)",
            wbs: "44",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "e0c4bad7-dbc2-47bf-95dd-b70a19f0b590",
            is_critical: true,
            planned_start_date: "2024-10-10",
            planned_end_date: "2024-10-15",
            duration: 6,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "MzrOVQjn6wjd25m6",
                    updated_by_id: undefined,
                    dependency_uuid: "f8078073-3118-4a81-9d97-40fdf5400892",
                    uuid: "5329b1c0-e7ab-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "m1AGpqQp7WjJRyWa",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "GO0YVbg7e0b7lpN2",
            uuid: "f1088afd-0dd0-4768-ac9d-631b54ea3a4a",
            name: "Reuse Of Loose Furniture ,Factory Finished Furniture & Chairs",
            wbs: "46",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "88e56ec9-e4ff-41dd-b15f-12b7f9957ae6",
            is_critical: true,
            planned_start_date: "2024-10-10",
            planned_end_date: "2024-10-16",
            duration: 7,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "81o9M5v3MOqx2Q4Y",
                    updated_by_id: undefined,
                    dependency_uuid: "6562fc95-98e7-419f-bd43-31221131b420",
                    uuid: "65d27550-e7ab-11ef-8158-77bdfda655ac",
                    lag: -6,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "8po94bYA0abarJe3",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "m1AGpqQp7WjJRyWa",
            uuid: "256c2cf4-57f1-4146-8b56-b19aaf8e51ad",
            name: "Plumbing Works",
            wbs: "47",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f1088afd-0dd0-4768-ac9d-631b54ea3a4a",
            is_critical: false,
            planned_start_date: "2024-09-18",
            planned_end_date: "2024-10-07",
            duration: 20,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 13,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "eNkErBq0omjaLJ09",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "771ae590-e7ab-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "5QgaWb4peObDwV9B",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "MmdEVjOl7BqDpz0a",
            uuid: "fa9aa145-c0c0-4b15-b538-23574b924d23",
            name: "Civil Contractor Finalisation",
            wbs: "12",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "ad0e87eb-2366-42f8-9dbe-00e141f386bf",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "wpme9yjZ7Yqn5Zr2",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "d9fb6260-e7a7-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "N6x1ojmR63qzOJWY",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "5QgaWb4peObDwV9B",
            uuid: "5b462065-b228-43ec-8718-8c4223eaef08",
            name: "POP Contractor Finalisation",
            wbs: "13",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "fa9aa145-c0c0-4b15-b538-23574b924d23",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "O1onaLqz2XqKBwpJ",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "ee7c4150-e7a7-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "nNOkZjdQEwqm4Jwg",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "N6x1ojmR63qzOJWY",
            uuid: "9f9c9dbd-3469-4525-bf2c-47c7a1e75c2a",
            name: "Painter Contractor Finalisation",
            wbs: "14",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "5b462065-b228-43ec-8718-8c4223eaef08",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "oPrQO0vkp7jG7Kyl",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "f9204110-e7a7-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "5eRzgvB3DwjpG7x6",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "nNOkZjdQEwqm4Jwg",
            uuid: "543340e0-4167-4170-8908-9889f4d2ca72",
            name: "Plumber Contractor Finalisation",
            wbs: "15",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "9f9c9dbd-3469-4525-bf2c-47c7a1e75c2a",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "B0yN2lvrngvrKPYd",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "02b4a590-e7a8-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "5BJQyqWZ0YjAL3Eg",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "5eRzgvB3DwjpG7x6",
            uuid: "39e6cb6d-63bc-466a-b7cf-823fae3855d8",
            name: "Carpentry",
            wbs: "16",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "543340e0-4167-4170-8908-9889f4d2ca72",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "7GgDXzqGlDbN1wnJ",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "0bd7f8c0-e7a8-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "6MWy2q2ma1j7aJYN",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "5BJQyqWZ0YjAL3Eg",
            uuid: "088dea2f-f380-4a6d-a010-8363c15660d3",
            name: "Glass Partition",
            wbs: "17",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "39e6cb6d-63bc-466a-b7cf-823fae3855d8",
            is_critical: false,
            planned_start_date: "2024-09-11",
            planned_end_date: "2024-09-12",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 38,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "9ng3XGvlpavK8oJ4",
                    updated_by_id: undefined,
                    dependency_uuid: "69f94148-b99d-4a9c-96a8-53adad68aad6",
                    uuid: "169e9bb0-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "zGwyoqAA83qBJ4pg",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "6MWy2q2ma1j7aJYN",
            uuid: "e7581f58-ab9f-4219-9a64-eb12942326a8",
            name: "Light Fixtures",
            wbs: "18",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "088dea2f-f380-4a6d-a010-8363c15660d3",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-04",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 46,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "k3B806qaVPbVaxlG",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "1de7d7b0-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "OyPDrb1ElEbzBEAG",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "zGwyoqAA83qBJ4pg",
            uuid: "5dc40037-ee8c-4a5c-aa81-b29d1fd210a9",
            name: "Electrical",
            wbs: "19",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "e7581f58-ab9f-4219-9a64-eb12942326a8",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-05",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Y6BnXdjwJ2vMWz4L",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "256d8070-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "pme9yjZ20Qjn5Zr2",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "OyPDrb1ElEbzBEAG",
            uuid: "4939ce46-a0b4-4aaa-b33b-dc1e7283d145",
            name: "HVAC",
            wbs: "20",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "5dc40037-ee8c-4a5c-aa81-b29d1fd210a9",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-05",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "OWwk3djRlpbaZARL",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "2c30c390-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "1onaLqzx6QvKBwpJ",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "pme9yjZ20Qjn5Zr2",
            uuid: "634a88f8-e702-4d71-a6ff-057ef3020f50",
            name: "Networking",
            wbs: "21",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "4939ce46-a0b4-4aaa-b33b-dc1e7283d145",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-05",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Z19zK2qVV2qB0k3l",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "3303e530-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "PrQO0vkaemqG7Kyl",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "1onaLqzx6QvKBwpJ",
            uuid: "f7fec775-165f-4220-9361-fa0112cbf84d",
            name: "Fire Fighting Works",
            wbs: "22",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "634a88f8-e702-4d71-a6ff-057ef3020f50",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-05",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "X76DlLjXD3j39ogd",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "380db880-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "0yN2lvrgy1jrKPYd",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "PrQO0vkaemqG7Kyl",
            uuid: "b2fa029f-f58f-49ef-816b-cc98a43075e1",
            name: "Fire Alaram & CCTV System",
            wbs: "23",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f7fec775-165f-4220-9361-fa0112cbf84d",
            is_critical: false,
            planned_start_date: "2024-09-04",
            planned_end_date: "2024-09-05",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "JaV5dKqD77jM2GgX",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "3e69fc70-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "GgDXzqGA8xvN1wnJ",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "0yN2lvrgy1jrKPYd",
            uuid: "7f58eb55-f597-42af-a2b6-fbce7bddb070",
            name: "Loose Furniture, Customised Furniture & Chairs",
            wbs: "24",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "b2fa029f-f58f-49ef-816b-cc98a43075e1",
            is_critical: false,
            planned_start_date: "2024-09-02",
            planned_end_date: "2024-09-05",
            duration: 4,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 45,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "apzYgovEN8j1X3Bk",
                    updated_by_id: undefined,
                    dependency_uuid: "bcec4a40-854b-4884-b037-58cb9a005ae7",
                    uuid: "42e46100-e7a8-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "3B806qaEypqVaxlG",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "ng3XGvlK1BbK8oJ4",
            uuid: "f621d2bc-62c6-4969-8d70-f2dbaa8d8eb7",
            name: "MEP-Shop drawings",
            wbs: "26",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "fca4121e-7ead-4328-9deb-bccc78fb331f",
            is_critical: false,
            planned_start_date: "2024-09-07",
            planned_end_date: "2024-09-07",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 42,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "ea3zM2bNENqBQXy1",
                    updated_by_id: undefined,
                    dependency_uuid: "fca4121e-7ead-4328-9deb-bccc78fb331f",
                    uuid: "7ce43fb0-e7a8-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FF",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "6BnXdjwDyJqMWz4L",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "3B806qaEypqVaxlG",
            uuid: "19ed7032-956d-48f3-982e-b741779acf05",
            name: "MEP-co-ordinated GFC",
            wbs: "27",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f621d2bc-62c6-4969-8d70-f2dbaa8d8eb7",
            is_critical: false,
            planned_start_date: "2024-09-07",
            planned_end_date: "2024-09-08",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 42,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Yd6MwBqLX0qV8JkK",
                    updated_by_id: "71YXeqPgmwjRAKPd",
                    dependency_uuid: "f621d2bc-62c6-4969-8d70-f2dbaa8d8eb7",
                    uuid: "c1649090-e7a8-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: "2025-02-10T12:23:02.882793Z",
                },
            ],
            comment_count: 0,
        },
        {
            id: "Wwk3djRONNqaZARL",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "6BnXdjwDyJqMWz4L",
            uuid: "b7b778ef-12c5-4630-8d9d-867efa8d7b25",
            name: "Elevations",
            wbs: "28",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "19ed7032-956d-48f3-982e-b741779acf05",
            is_critical: false,
            planned_start_date: "2024-09-02",
            planned_end_date: "2024-09-07",
            duration: 6,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 38,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "7GgDXzqGldbN1wnJ",
                    updated_by_id: "71YXeqPgmwjRAKPd",
                    dependency_uuid: "fca4121e-7ead-4328-9deb-bccc78fb331f",
                    uuid: "b501ad50-e7a9-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: "2025-02-10T12:23:12.730434Z",
                },
            ],
            comment_count: 0,
        },
        {
            id: "19zK2qVA0djB0k3l",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "Wwk3djRONNqaZARL",
            uuid: "69f94148-b99d-4a9c-96a8-53adad68aad6",
            name: "Detail Drawing",
            wbs: "29",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "b7b778ef-12c5-4630-8d9d-867efa8d7b25",
            is_critical: false,
            planned_start_date: "2024-09-09",
            planned_end_date: "2024-09-10",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 38,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "9ng3XGvlp0vK8oJ4",
                    updated_by_id: undefined,
                    dependency_uuid: "b7b778ef-12c5-4630-8d9d-867efa8d7b25",
                    uuid: "d3a63870-e7a9-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "76DlLjX90Xq39ogd",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "19zK2qVA0djB0k3l",
            uuid: "34f33508-bdc0-4b29-9afd-39fea02e2510",
            name: "Finishes Matrix and Make/ sample list",
            wbs: "30",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "69f94148-b99d-4a9c-96a8-53adad68aad6",
            is_critical: false,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-08",
            duration: 4,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 39,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "k3B806qaVzbVaxlG",
                    updated_by_id: undefined,
                    dependency_uuid: "fca4121e-7ead-4328-9deb-bccc78fb331f",
                    uuid: "f2e46b80-e7a9-11ef-8158-77bdfda655ac",
                    lag: -2,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "aV5dKqDA80bM2GgX",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "76DlLjX90Xq39ogd",
            uuid: "002bdc0a-a291-48f7-b4fc-abb3fc9267a5",
            name: "3D",
            wbs: "31",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "34f33508-bdc0-4b29-9afd-39fea02e2510",
            is_critical: false,
            planned_start_date: "2024-09-07",
            planned_end_date: "2024-09-09",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 39,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Y6BnXdjwJnvMWz4L",
                    updated_by_id: undefined,
                    dependency_uuid: "34f33508-bdc0-4b29-9afd-39fea02e2510",
                    uuid: "01bf8540-e7aa-11ef-8158-77bdfda655ac",
                    lag: -2,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "nwAN0b70DwvQ65DP",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "pzYgovE486b1X3Bk",
            uuid: "d354e981-bf62-450d-bfba-afa97ef809b4",
            name: "Temporary arrangements for lights and water supply",
            wbs: "33",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "7c683ac2-5dd8-43b8-917b-4d061d7778f2",
            is_critical: false,
            planned_start_date: "2024-09-11",
            planned_end_date: "2024-09-15",
            duration: 5,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 35,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Z19zK2qVVNqB0k3l",
                    updated_by_id: undefined,
                    dependency_uuid: "7c683ac2-5dd8-43b8-917b-4d061d7778f2",
                    uuid: "3882af80-e7aa-11ef-8158-77bdfda655ac",
                    lag: -4,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "71YXeqPaElbRAKPd",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "DeOyQqeY4aqm4LrW",
            uuid: "5c47e6fa-8d5c-4e96-bc88-7043a913a0ac",
            name: "Flooring And Wall Cladding",
            wbs: "39",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "484f648a-8f08-4ea4-8371-f7fc899c5e7e",
            is_critical: false,
            planned_start_date: "2024-09-20",
            planned_end_date: "2024-10-04",
            duration: 15,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 16,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "Yd6MwBqLXBqV8JkK",
                    updated_by_id: "71YXeqPgmwjRAKPd",
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "f8a98310-e7aa-11ef-8158-77bdfda655ac",
                    lag: -3,
                    type: "FS",
                    updated_at: "2025-02-10T12:31:55.302847Z",
                },
            ],
            comment_count: 0,
        },
        {
            id: "1o9M5v30wrjx2Q4Y",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "1ZnElq6DXgvo35Bg",
            uuid: "d227fe36-3dd9-49f7-95ba-2b4669295afc",
            name: "Panelling/cladding work & Other Carpentry Works",
            wbs: "42",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f8078073-3118-4a81-9d97-40fdf5400892",
            is_critical: false,
            planned_start_date: "2024-09-22",
            planned_end_date: "2024-10-14",
            duration: 23,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 6,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "GDeOyQqe7Lvm4LrW",
                    updated_by_id: undefined,
                    dependency_uuid: "f067dd2c-d059-4a06-bd34-5515ad834b8d",
                    uuid: "2f413080-e7ab-11ef-8158-77bdfda655ac",
                    lag: -11,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "NkErBq0zGyvaLJ09",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "1o9M5v30wrjx2Q4Y",
            uuid: "e0c4bad7-dbc2-47bf-95dd-b70a19f0b590",
            name: "Doors",
            wbs: "43",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "d227fe36-3dd9-49f7-95ba-2b4669295afc",
            is_critical: false,
            planned_start_date: "2024-09-28",
            planned_end_date: "2024-10-18",
            duration: 21,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 2,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "a71YXeqPNxvRAKPd",
                    updated_by_id: undefined,
                    dependency_uuid: "f067dd2c-d059-4a06-bd34-5515ad834b8d",
                    uuid: "431b4820-e7ab-11ef-8158-77bdfda655ac",
                    lag: -5,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "GO0YVbg7e0b7lpN2",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "gPVoxb8WENq91RA4",
            uuid: "88e56ec9-e4ff-41dd-b15f-12b7f9957ae6",
            name: "Painting Works",
            wbs: "45",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "6562fc95-98e7-419f-bd43-31221131b420",
            is_critical: false,
            planned_start_date: "2024-10-08",
            planned_end_date: "2024-10-15",
            duration: 8,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "R1ZnElq62Mqo35Bg",
                    updated_by_id: undefined,
                    dependency_uuid: "484f648a-8f08-4ea4-8371-f7fc899c5e7e",
                    uuid: "59cf0ca0-e7ab-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "P1DN7jy4rJvzn0aA",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "wp8LYbxVWJjnlGK6",
            uuid: "488550a5-cf7c-4a5d-9031-35634868ec52",
            name: "Eletectrical Works",
            wbs: "49",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "bc964dff-d860-425d-b26b-4063444d4bb6",
            is_critical: false,
            planned_start_date: "2024-09-13",
            planned_end_date: "2024-10-15",
            duration: 33,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "LGO0YVbg6Eq7lpN2",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "956060c0-e7ab-11ef-8158-77bdfda655ac",
                    lag: -10,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "Km6Wyq907wjZ7d13",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "P1DN7jy4rJvzn0aA",
            uuid: "155804da-487f-488c-979c-09cb93f4b10f",
            name: "HVAC Works",
            wbs: "50",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "488550a5-cf7c-4a5d-9031-35634868ec52",
            is_critical: false,
            planned_start_date: "2024-09-13",
            planned_end_date: "2024-10-15",
            duration: 33,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "om1AGpqQG3vJRyWa",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "a60cb810-e7ab-11ef-8158-77bdfda655ac",
                    lag: -10,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "Ed43KjK9wzbNOzGe",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "Km6Wyq907wjZ7d13",
            uuid: "22c7429a-e4e6-4161-b68f-c3deda836037",
            name: "Fire Fighting Works",
            wbs: "51",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "155804da-487f-488c-979c-09cb93f4b10f",
            is_critical: false,
            planned_start_date: "2024-09-13",
            planned_end_date: "2024-10-03",
            duration: 21,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 17,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "R8po94bYErbarJe3",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "bb792f80-e7ab-11ef-8158-77bdfda655ac",
                    lag: -10,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "rzKaQv51Vov17YWX",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "Ed43KjK9wzbNOzGe",
            uuid: "9e25e29d-d3a8-4cc4-ac5b-b2187fe55104",
            name: "Fire Alaram & CCTV System",
            wbs: "52",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "22c7429a-e4e6-4161-b68f-c3deda836037",
            is_critical: false,
            planned_start_date: "2024-09-13",
            planned_end_date: "2024-10-15",
            duration: 33,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "5wp8LYbxd0bnlGK6",
                    updated_by_id: undefined,
                    dependency_uuid: "fc36c204-a645-40b2-a9cf-5a7348f04871",
                    uuid: "cb449cb0-e7ab-11ef-8158-77bdfda655ac",
                    lag: -10,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "xl8KXjpX9Zj2mpPM",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "rBAdKboVynqLe7Og",
            uuid: "25834a8b-edc7-4d4a-b03b-05933d51801c",
            name: "HANDOVER TO CLIENT",
            wbs: "54",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
            is_critical: true,
            planned_start_date: "2024-10-18",
            planned_end_date: "2024-10-20",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "2Km6Wyq9MaqZ7d13",
                    updated_by_id: undefined,
                    dependency_uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
                    uuid: "12fa9d20-e7ac-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "MmdEVjOlDBqDpz0a",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "xl8KXjpX9Zj2mpPM",
            uuid: "7abc0bbf-4802-4650-bd0b-c1dd3e0c51fb",
            name: "Snaglist Prepration",
            wbs: "55",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "25834a8b-edc7-4d4a-b03b-05933d51801c",
            is_critical: false,
            planned_start_date: "2024-10-15",
            planned_end_date: "2024-10-15",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "yEd43KjKVgvNOzGe",
                    updated_by_id: undefined,
                    dependency_uuid: "bc964dff-d860-425d-b26b-4063444d4bb6",
                    uuid: "233790d0-e7ac-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "5QgaWb4pRObDwV9B",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "MmdEVjOlDBqDpz0a",
            uuid: "f17b332d-9742-4d08-8ccd-a9af78925e23",
            name: "As Built Drawing Submissions",
            wbs: "56",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "7abc0bbf-4802-4650-bd0b-c1dd3e0c51fb",
            is_critical: false,
            planned_start_date: "2024-10-15",
            planned_end_date: "2024-10-15",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 5,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "GrzKaQv5V2j17YWX",
                    updated_by_id: undefined,
                    dependency_uuid: "bc964dff-d860-425d-b26b-4063444d4bb6",
                    uuid: "2ce0b5d0-e7ac-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "N6x1ojmRo3qzOJWY",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "5QgaWb4pRObDwV9B",
            uuid: "60707280-d332-4675-b642-2409c32fed86",
            name: "Handover Document Submissions",
            wbs: "57",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "f17b332d-9742-4d08-8ccd-a9af78925e23",
            is_critical: false,
            planned_start_date: "2024-10-19",
            planned_end_date: "2024-10-19",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 1,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "GrBAdKboyXjLe7Og",
                    updated_by_id: undefined,
                    dependency_uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
                    uuid: "35127d10-e7ac-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "nNOkZjdQ4wqm4Jwg",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "N6x1ojmRo3qzOJWY",
            uuid: "a66d961e-3c61-476b-868b-3e12a17acd2a",
            name: "Snaglist Closure",
            wbs: "58",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "60707280-d332-4675-b642-2409c32fed86",
            is_critical: false,
            planned_start_date: "2024-10-19",
            planned_end_date: "2024-10-19",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 1,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "3xl8KXjp98q2mpPM",
                    updated_by_id: undefined,
                    dependency_uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
                    uuid: "3ccc5530-e7ac-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "5eRzgvB35wjpG7x6",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "nNOkZjdQ4wqm4Jwg",
            uuid: "a32e4a63-259f-428a-a081-7d7928304c7f",
            name: "Client Feedback and Completion Letter",
            wbs: "59",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "a66d961e-3c61-476b-868b-3e12a17acd2a",
            is_critical: false,
            planned_start_date: "2024-10-19",
            planned_end_date: "2024-10-19",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 1,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "JMmdEVjODlqDpz0a",
                    updated_by_id: undefined,
                    dependency_uuid: "3fe753be-7b5a-47b9-914d-3aefc483fac1",
                    uuid: "4472a550-e7ac-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "GO0YVbg760b7lpN2",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: undefined,
            uuid: "bcec4a40-854b-4884-b037-58cb9a005ae7",
            name: "Appointment of contractor",
            wbs: "1",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: undefined,
            is_critical: true,
            planned_start_date: "2024-09-01",
            planned_end_date: "2024-09-01",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [],
            comment_count: 0,
        },
        {
            id: "Km6Wyq90MwjZ7d13",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "P1DN7jy4WJvzn0aA",
            uuid: "d7ee0933-d6c0-4b1e-8827-5d9fc65600a9",
            name: "Providing the GFC dwgs, Sign-off on Final Layouts",
            wbs: "6",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "70a74089-1c1e-446b-84b9-5409db8acf8d",
            is_critical: false,
            planned_start_date: "2024-09-02",
            planned_end_date: "2024-09-07",
            duration: 6,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 38,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "DnNOkZjd82jm4Jwg",
                    updated_by_id: undefined,
                    dependency_uuid: "bcec4a40-854b-4884-b037-58cb9a005ae7",
                    uuid: "85722620-e7a7-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "rzKaQv51Mov17YWX",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "Ed43KjK9VzbNOzGe",
            uuid: "078d6e2a-c00e-4f5a-9aec-ebe242ffbc99",
            name: "Advance payment release milestone",
            wbs: "8",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "a92a54b1-7ecb-4edc-ab0e-fae59aa3e6cb",
            is_critical: false,
            planned_start_date: "2024-09-03",
            planned_end_date: "2024-09-05",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 43,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "o5BJQyqWP9bAL3Eg",
                    updated_by_id: undefined,
                    dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                    uuid: "9f19fd50-e7a7-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "wp8LYbxVdJjnlGK6",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "8po94bYAEabarJe3",
            uuid: "9749bb39-cbef-494b-8801-7cbd6133aee0",
            name: "Reciept of Documents for MCGM approval from Client",
            wbs: "4",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "1b6d44f3-aca2-4bd4-ad29-4ce440177fc8",
            is_critical: true,
            planned_start_date: "2024-09-05",
            planned_end_date: "2024-09-05",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "l5QgaWb4n5jDwV9B",
                    updated_by_id: undefined,
                    dependency_uuid: "1b6d44f3-aca2-4bd4-ad29-4ce440177fc8",
                    uuid: "6a9132b0-e7a7-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "Ed43KjK9VzbNOzGe",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "Km6Wyq90MwjZ7d13",
            uuid: "a92a54b1-7ecb-4edc-ab0e-fae59aa3e6cb",
            name: "Approval of drawing from Brookfield",
            wbs: "7",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "d7ee0933-d6c0-4b1e-8827-5d9fc65600a9",
            is_critical: false,
            planned_start_date: "2024-09-07",
            planned_end_date: "2024-09-09",
            duration: 3,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 41,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "E5eRzgvB6QvpG7x6",
                    updated_by_id: undefined,
                    dependency_uuid: "d7ee0933-d6c0-4b1e-8827-5d9fc65600a9",
                    uuid: "8c2e6460-e7a7-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "MmdEVjOl7BqDpz0a",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "xl8KXjpX2Zj2mpPM",
            uuid: "ad0e87eb-2366-42f8-9dbe-00e141f386bf",
            name: "Site takeover from client",
            wbs: "11",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "64ac3723-99ec-465b-8d5e-1ea42172a93a",
            is_critical: true,
            planned_start_date: "2024-09-13",
            planned_end_date: "2024-09-13",
            duration: 1,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "2OyPDrb1gMjzBEAG",
                    updated_by_id: undefined,
                    dependency_uuid: "64ac3723-99ec-465b-8d5e-1ea42172a93a",
                    uuid: "cf896f20-e7a7-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "m1AGpqQpGWjJRyWa",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "GO0YVbg760b7lpN2",
            uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
            name: "Contract signoff & Release of LOI / Purchase order from Client to DSIPL",
            wbs: "2",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "bcec4a40-854b-4884-b037-58cb9a005ae7",
            is_critical: true,
            planned_start_date: "2024-09-02",
            planned_end_date: "2024-09-03",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "3xl8KXjpexq2mpPM",
                    updated_by_id: undefined,
                    dependency_uuid: "1b6d44f3-aca2-4bd4-ad29-4ce440177fc8",
                    uuid: "29aa5c40-e7a7-11ef-8158-77bdfda655ac",
                    lag: 0,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "8po94bYAEabarJe3",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "m1AGpqQpGWjJRyWa",
            uuid: "1b6d44f3-aca2-4bd4-ad29-4ce440177fc8",
            name: "Approval Of final Furniture Layout",
            wbs: "3",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
            is_critical: true,
            planned_start_date: "2024-08-31",
            planned_end_date: "2024-09-03",
            duration: 4,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                // {
                //     id: "JMmdEVjOPzqDpz0a",
                //     updated_by_id: "71YXeqPgmwjRAKPd",
                //     dependency_uuid: "c6f82170-f7e6-419a-82c6-3f2a60d713d6",
                //     uuid: "4a42c820-e7a7-11ef-8158-77bdfda655ac",
                //     lag: 0,
                //     type: "FF",
                //     updated_at: "2025-02-10T12:05:47.423249Z",
                // },
            ],
            comment_count: 0,
        },
        {
            id: "P1DN7jy4WJvzn0aA",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "wp8LYbxVdJjnlGK6",
            uuid: "70a74089-1c1e-446b-84b9-5409db8acf8d",
            name: "Submission of Documents for MCGM approval",
            wbs: "5",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "9749bb39-cbef-494b-8801-7cbd6133aee0",
            is_critical: true,
            planned_start_date: "2024-09-07",
            planned_end_date: "2024-09-08",
            duration: 2,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "EN6x1ojm8evzOJWY",
                    updated_by_id: undefined,
                    dependency_uuid: "9749bb39-cbef-494b-8801-7cbd6133aee0",
                    uuid: "78584460-e7a7-11ef-8158-77bdfda655ac",
                    lag: 1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "xl8KXjpX2Zj2mpPM",
            parent_id: "7GgDXzqGRjN1wnJ5",
            prev_sibling_id: "rBAdKboV6nqLe7Og",
            uuid: "64ac3723-99ec-465b-8d5e-1ea42172a93a",
            name: "Reciept of MCGM approvals",
            wbs: "10",
            color: "#9689B2",
            is_parent: false,
            parent_uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            prev_sibling_uuid: "4c984be3-79d2-4491-afbe-20c99feaa925",
            is_critical: true,
            planned_start_date: "2024-09-08",
            planned_end_date: "2024-09-12",
            duration: 5,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: undefined,
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [
                {
                    id: "MzGwyoqAnNbBJ4pg",
                    updated_by_id: undefined,
                    dependency_uuid: "70a74089-1c1e-446b-84b9-5409db8acf8d",
                    uuid: "be17cc00-e7a7-11ef-8158-77bdfda655ac",
                    lag: -1,
                    type: "FS",
                    updated_at: undefined,
                },
            ],
            comment_count: 0,
        },
        {
            id: "7GgDXzqGRjN1wnJ5",
            parent_id: undefined,
            prev_sibling_id: undefined,
            uuid: "478e01dc-6834-458d-a754-989bad1b112e",
            name: "Root Activity",
            wbs: "0",
            color: "#000000",
            is_parent: true,
            parent_uuid: undefined,
            prev_sibling_uuid: undefined,
            is_critical: false,
            planned_start_date: undefined,
            planned_end_date: "2024-10-20",
            duration: 0,
            actual_start_date: undefined,
            actual_end_date: undefined,
            projected_start_date: undefined,
            projected_end_date: "2025-04-01",
            completion_percent: 0,
            slack: 0,
            assignees: [],
            organizations: [],
            attachments: [],
            dependencies: [],
            comment_count: 0,
        },
    ],
};
*/

function process_schedule(schedule: IScheduleData): IScheduleData {
    /*
    Function can be used to debug the schedule data by converting uuids to integers
    */
    let uuid_map = new Map<string, string>();
    uuid_map.set(schedule.uuid, "0");
    schedule.uuid = "0";
    let count = 1;
    schedule.activities.forEach((activity) => {
        if (activity.uuid && uuid_map.has(activity.uuid)) {
            let id = uuid_map.get(activity.uuid);
            if (id !== undefined) {
                activity.uuid = id.toString();
            }
        } else {
            uuid_map.set(activity.uuid, count.toString());
            activity.uuid = count.toString();
            count++;
        }
        if (activity.parent_uuid && uuid_map.has(activity.parent_uuid)) {
            activity.parent_uuid = uuid_map
                .get(activity.parent_uuid)
                ?.toString();
        } else if (activity.parent_uuid) {
            uuid_map.set(activity.parent_uuid, count.toString());
            activity.parent_uuid = count.toString();
            count++;
        }

        if (activity.dependencies) {
            activity.dependencies.forEach((dependency) => {
                if (
                    dependency.dependency_uuid &&
                    uuid_map.has(dependency.dependency_uuid)
                ) {
                    let id = uuid_map.get(dependency.dependency_uuid);
                    if (id !== undefined) {
                        dependency.dependency_uuid = id.toString();
                    }
                } else {
                    uuid_map.set(dependency.dependency_uuid, count.toString());
                    dependency.dependency_uuid = count.toString();
                    count++;
                }
            });
        }
        if (activity.uuid == "56") {
            console.log(activity);
        }
    });
    return schedule;
}

// ProjectScheduleProcessor.process_project_schedule_data(process_schedule(project_schedule));
